// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function CompleteTodo(arg1:number):Promise<models.TodoResponse>;

export function CreatePurpose(arg1:string,arg2:string,arg3:string):Promise<any>;

export function CreateTodo(arg1:models.TodoRequest):Promise<models.TodoResponse>;

export function DeletePurpose(arg1:number):Promise<any>;

export function DeleteTodo(arg1:number):Promise<main.DeleteResponse>;

export function GetActiveTimer():Promise<models.TimerResponse>;

export function GetAllPurposes():Promise<main.PurposeResponse>;

export function GetAllTodos():Promise<main.TodosResponse>;

export function GetStatistics(arg1:string):Promise<main.StatsResponse>;

export function GetTodayRecords():Promise<any>;

export function GetTodosByStatus(arg1:string):Promise<main.TodosResponse>;

export function Greet(arg1:string):Promise<string>;

export function StartTimer(arg1:models.TimerRequest):Promise<models.TimerResponse>;

export function StartTodo(arg1:number):Promise<models.TodoResponse>;

export function StopTimer(arg1:number):Promise<models.TimerResponse>;

export function UpdateTodo(arg1:number,arg2:models.TodoRequest):Promise<models.TodoResponse>;
