// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteTodo(arg1) {
  return window['go']['main']['App']['CompleteTodo'](arg1);
}

export function CreatePurpose(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePurpose'](arg1, arg2, arg3);
}

export function CreateTodo(arg1) {
  return window['go']['main']['App']['CreateTodo'](arg1);
}

export function DeletePurpose(arg1) {
  return window['go']['main']['App']['DeletePurpose'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetActiveTimer() {
  return window['go']['main']['App']['GetActiveTimer']();
}

export function GetAllPurposes() {
  return window['go']['main']['App']['GetAllPurposes']();
}

export function GetAllTodos() {
  return window['go']['main']['App']['GetAllTodos']();
}

export function GetStatistics(arg1) {
  return window['go']['main']['App']['GetStatistics'](arg1);
}

export function GetTodayRecords() {
  return window['go']['main']['App']['GetTodayRecords']();
}

export function GetTodosByStatus(arg1) {
  return window['go']['main']['App']['GetTodosByStatus'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartTimer(arg1) {
  return window['go']['main']['App']['StartTimer'](arg1);
}

export function StartTodo(arg1) {
  return window['go']['main']['App']['StartTodo'](arg1);
}

export function StopTimer(arg1) {
  return window['go']['main']['App']['StopTimer'](arg1);
}

export function UpdateTodo(arg1, arg2) {
  return window['go']['main']['App']['UpdateTodo'](arg1, arg2);
}
